namespace Create_Monster.Form_Mob
{
    partial class MobForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges1 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges2 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges3 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges4 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges5 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges6 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges7 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges8 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges21 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges22 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges9 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges10 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges11 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges12 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges19 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges20 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges13 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges14 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges15 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges16 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges17 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges18 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges27 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges28 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges23 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges24 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges25 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges26 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MobForm));
            btnSaveCrop = new Guna.UI2.WinForms.Guna2GradientButton();
            picDefault = new Guna.UI2.WinForms.Guna2PictureBox();
            openHDSD = new Guna.UI2.WinForms.Guna2GradientButton();
            guna2Panel3 = new Guna.UI2.WinForms.Guna2Panel();
            guna2Panel2 = new Guna.UI2.WinForms.Guna2Panel();
            guna2Panel5 = new Guna.UI2.WinForms.Guna2Panel();
            btnImportImage = new Guna.UI2.WinForms.Guna2GradientButton();
            guna2Panel4 = new Guna.UI2.WinForms.Guna2Panel();
            btnFastCrop = new Guna.UI2.WinForms.Guna2GradientButton();
            btnEffectForm = new Guna.UI2.WinForms.Guna2GradientButton();
            txtIdMob = new Guna.UI2.WinForms.Guna2TextBox();
            cbHasMobId = new Guna.UI2.WinForms.Guna2CheckBox();
            UpdateExpired = new System.Windows.Forms.Timer(components);
            guna2Panel1 = new Guna.UI2.WinForms.Guna2Panel();
            maximize2 = new Maximize();
            guna2ControlBox2 = new Guna.UI2.WinForms.Guna2ControlBox();
            guna2ControlBox1 = new Guna.UI2.WinForms.Guna2ControlBox();
            label1 = new Label();
            guna2DragControl1 = new Guna.UI2.WinForms.Guna2DragControl(components);
            openFileDialog1 = new OpenFileDialog();
            guna2BorderlessForm1 = new Guna.UI2.WinForms.Guna2BorderlessForm(components);
            guna2AnimateWindow1 = new Guna.UI2.WinForms.Guna2AnimateWindow(components);
            checkSaveData = new System.Windows.Forms.Timer(components);
            ((System.ComponentModel.ISupportInitialize)picDefault).BeginInit();
            guna2Panel3.SuspendLayout();
            guna2Panel2.SuspendLayout();
            guna2Panel5.SuspendLayout();
            guna2Panel4.SuspendLayout();
            guna2Panel1.SuspendLayout();
            SuspendLayout();
            btnSaveCrop.BorderRadius = 5;
            btnSaveCrop.CustomizableEdges = customizableEdges1;
            btnSaveCrop.DisabledState.BorderColor = Color.DarkGray;
            btnSaveCrop.DisabledState.CustomBorderColor = Color.DarkGray;
            btnSaveCrop.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnSaveCrop.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            btnSaveCrop.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnSaveCrop.FillColor = Color.FromArgb(144, 118, 147);
            btnSaveCrop.FillColor2 = Color.FromArgb(119, 95, 133);
            btnSaveCrop.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            btnSaveCrop.ForeColor = Color.White;
            btnSaveCrop.Location = new Point(128, 15);
            btnSaveCrop.Name = "btnSaveCrop";
            btnSaveCrop.ShadowDecoration.CustomizableEdges = customizableEdges2;
            btnSaveCrop.Size = new Size(104, 36);
            btnSaveCrop.TabIndex = 7;
            btnSaveCrop.Text = "Save Crop";
            btnSaveCrop.Click += btnSaveCrop_Click;
            picDefault.CustomizableEdges = customizableEdges3;
            picDefault.ImageRotate = 0F;
            picDefault.Location = new Point(2, 3);
            picDefault.Name = "picDefault";
            picDefault.ShadowDecoration.CustomizableEdges = customizableEdges4;
            picDefault.Size = new Size(773, 425);
            picDefault.SizeMode = PictureBoxSizeMode.AutoSize;
            picDefault.TabIndex = 0;
            picDefault.TabStop = false;
            picDefault.UseTransparentBackground = true;
            picDefault.Paint += picDefault_Paint;
            picDefault.MouseDown += picDefault_MouseDown;
            picDefault.MouseLeave += picDefault_MouseLeave;
            picDefault.MouseMove += picDefault_MouseMove;
            picDefault.MouseUp += picDefault_MouseUp;
            openHDSD.BorderRadius = 5;
            openHDSD.CustomizableEdges = customizableEdges5;
            openHDSD.DisabledState.BorderColor = Color.DarkGray;
            openHDSD.DisabledState.CustomBorderColor = Color.DarkGray;
            openHDSD.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            openHDSD.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            openHDSD.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            openHDSD.FillColor = Color.FromArgb(144, 118, 147);
            openHDSD.FillColor2 = Color.FromArgb(119, 95, 133);
            openHDSD.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            openHDSD.ForeColor = Color.White;
            openHDSD.Location = new Point(458, 15);
            openHDSD.Name = "openHDSD";
            openHDSD.ShadowDecoration.CustomizableEdges = customizableEdges6;
            openHDSD.Size = new Size(104, 36);
            openHDSD.TabIndex = 11;
            openHDSD.Text = "HDSD";
            openHDSD.Click += openHDSD_Click;
            guna2Panel3.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            guna2Panel3.AutoScroll = true;
            guna2Panel3.Controls.Add(picDefault);
            guna2Panel3.CustomizableEdges = customizableEdges7;
            guna2Panel3.Location = new Point(13, 3);
            guna2Panel3.Name = "guna2Panel3";
            guna2Panel3.ShadowDecoration.CustomizableEdges = customizableEdges8;
            guna2Panel3.Size = new Size(776, 428);
            guna2Panel3.TabIndex = 10;
            guna2Panel3.UseTransparentBackground = true;
            guna2Panel2.BackColor = Color.Transparent;
            guna2Panel2.Controls.Add(guna2Panel5);
            guna2Panel2.Controls.Add(btnImportImage);
            guna2Panel2.Controls.Add(guna2Panel4);
            guna2Panel2.CustomizableEdges = customizableEdges21;
            guna2Panel2.Dock = DockStyle.Fill;
            guna2Panel2.Location = new Point(0, 36);
            guna2Panel2.Name = "guna2Panel2";
            guna2Panel2.ShadowDecoration.CustomizableEdges = customizableEdges22;
            guna2Panel2.Size = new Size(801, 503);
            guna2Panel2.TabIndex = 3;
            guna2Panel2.UseTransparentBackground = true;
            guna2Panel5.Controls.Add(guna2Panel3);
            guna2Panel5.CustomizableEdges = customizableEdges9;
            guna2Panel5.Dock = DockStyle.Fill;
            guna2Panel5.Location = new Point(0, 66);
            guna2Panel5.Name = "guna2Panel5";
            guna2Panel5.ShadowDecoration.CustomizableEdges = customizableEdges10;
            guna2Panel5.Size = new Size(801, 437);
            guna2Panel5.TabIndex = 17;
            guna2Panel5.UseTransparentBackground = true;
            btnImportImage.BorderRadius = 5;
            btnImportImage.CustomizableEdges = customizableEdges11;
            btnImportImage.DisabledState.BorderColor = Color.DarkGray;
            btnImportImage.DisabledState.CustomBorderColor = Color.DarkGray;
            btnImportImage.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnImportImage.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            btnImportImage.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnImportImage.FillColor = Color.FromArgb(144, 118, 147);
            btnImportImage.FillColor2 = Color.FromArgb(119, 95, 133);
            btnImportImage.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            btnImportImage.ForeColor = Color.White;
            btnImportImage.Location = new Point(18, 15);
            btnImportImage.Name = "btnImportImage";
            btnImportImage.ShadowDecoration.CustomizableEdges = customizableEdges12;
            btnImportImage.Size = new Size(104, 36);
            btnImportImage.TabIndex = 5;
            btnImportImage.Text = "Import Image";
            btnImportImage.Click += btnImportImage_Click;
            guna2Panel4.Controls.Add(btnFastCrop);
            guna2Panel4.Controls.Add(btnSaveCrop);
            guna2Panel4.Controls.Add(btnEffectForm);
            guna2Panel4.Controls.Add(txtIdMob);
            guna2Panel4.Controls.Add(openHDSD);
            guna2Panel4.Controls.Add(cbHasMobId);
            guna2Panel4.CustomizableEdges = customizableEdges19;
            guna2Panel4.Dock = DockStyle.Top;
            guna2Panel4.Location = new Point(0, 0);
            guna2Panel4.Name = "guna2Panel4";
            guna2Panel4.ShadowDecoration.CustomizableEdges = customizableEdges20;
            guna2Panel4.Size = new Size(801, 66);
            guna2Panel4.TabIndex = 16;
            btnFastCrop.BorderRadius = 5;
            btnFastCrop.CustomizableEdges = customizableEdges13;
            btnFastCrop.DisabledState.BorderColor = Color.DarkGray;
            btnFastCrop.DisabledState.CustomBorderColor = Color.DarkGray;
            btnFastCrop.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnFastCrop.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            btnFastCrop.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnFastCrop.FillColor = Color.FromArgb(144, 118, 147);
            btnFastCrop.FillColor2 = Color.FromArgb(119, 95, 133);
            btnFastCrop.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            btnFastCrop.ForeColor = Color.White;
            btnFastCrop.Location = new Point(238, 15);
            btnFastCrop.Name = "btnFastCrop";
            btnFastCrop.ShadowDecoration.CustomizableEdges = customizableEdges14;
            btnFastCrop.Size = new Size(104, 36);
            btnFastCrop.TabIndex = 16;
            btnFastCrop.Text = "Fast Crop";
            btnFastCrop.Click += btnFastCrop_Click;
            btnEffectForm.BorderRadius = 5;
            btnEffectForm.CustomizableEdges = customizableEdges15;
            btnEffectForm.DisabledState.BorderColor = Color.DarkGray;
            btnEffectForm.DisabledState.CustomBorderColor = Color.DarkGray;
            btnEffectForm.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            btnEffectForm.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            btnEffectForm.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            btnEffectForm.FillColor = Color.FromArgb(144, 118, 147);
            btnEffectForm.FillColor2 = Color.FromArgb(119, 95, 133);
            btnEffectForm.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            btnEffectForm.ForeColor = Color.White;
            btnEffectForm.Location = new Point(348, 15);
            btnEffectForm.Name = "btnEffectForm";
            btnEffectForm.ShadowDecoration.CustomizableEdges = customizableEdges16;
            btnEffectForm.Size = new Size(104, 36);
            btnEffectForm.TabIndex = 6;
            btnEffectForm.Text = "From Mob";
            btnEffectForm.Click += btnEffectForm_Click;
            txtIdMob.Animated = true;
            txtIdMob.BorderColor = Color.FromArgb(119, 95, 133);
            txtIdMob.BorderRadius = 5;
            txtIdMob.CustomizableEdges = customizableEdges17;
            txtIdMob.DefaultText = "";
            txtIdMob.DisabledState.BorderColor = Color.FromArgb(208, 208, 208);
            txtIdMob.DisabledState.FillColor = Color.FromArgb(226, 226, 226);
            txtIdMob.DisabledState.ForeColor = Color.FromArgb(138, 138, 138);
            txtIdMob.DisabledState.PlaceholderForeColor = Color.FromArgb(138, 138, 138);
            txtIdMob.FocusedState.BorderColor = Color.FromArgb(94, 148, 255);
            txtIdMob.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
            txtIdMob.HoverState.BorderColor = Color.FromArgb(94, 148, 255);
            txtIdMob.Location = new Point(693, 15);
            txtIdMob.Name = "txtIdMob";
            txtIdMob.PasswordChar = '\0';
            txtIdMob.PlaceholderForeColor = Color.Gray;
            txtIdMob.PlaceholderText = "ID Mob";
            txtIdMob.SelectedText = "";
            txtIdMob.ShadowDecoration.CustomizableEdges = customizableEdges18;
            txtIdMob.Size = new Size(62, 18);
            txtIdMob.TabIndex = 1;
            txtIdMob.KeyPress += txtIdMob_KeyPress;
            cbHasMobId.Animated = true;
            cbHasMobId.AutoSize = true;
            cbHasMobId.CheckedState.BorderColor = Color.FromArgb(94, 148, 255);
            cbHasMobId.CheckedState.BorderRadius = 0;
            cbHasMobId.CheckedState.BorderThickness = 0;
            cbHasMobId.CheckedState.FillColor = Color.FromArgb(94, 148, 255);
            cbHasMobId.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            cbHasMobId.ForeColor = Color.FromArgb(144, 118, 147);
            cbHasMobId.Location = new Point(568, 15);
            cbHasMobId.Name = "cbHasMobId";
            cbHasMobId.Size = new Size(119, 19);
            cbHasMobId.TabIndex = 15;
            cbHasMobId.Text = "Data Has Mob ID";
            cbHasMobId.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            cbHasMobId.UncheckedState.BorderRadius = 0;
            cbHasMobId.UncheckedState.BorderThickness = 0;
            cbHasMobId.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            UpdateExpired.Enabled = true;
            UpdateExpired.Interval = 1000;
            UpdateExpired.Tick += UpdateExpired_Tick;
            guna2Panel1.BackColor = Color.FromArgb(144, 118, 147);
            guna2Panel1.Controls.Add(maximize2);
            guna2Panel1.Controls.Add(guna2ControlBox2);
            guna2Panel1.Controls.Add(guna2ControlBox1);
            guna2Panel1.Controls.Add(label1);
            guna2Panel1.CustomizableEdges = customizableEdges27;
            guna2Panel1.Dock = DockStyle.Top;
            guna2Panel1.Location = new Point(0, 0);
            guna2Panel1.Name = "guna2Panel1";
            guna2Panel1.ShadowDecoration.CustomizableEdges = customizableEdges28;
            guna2Panel1.Size = new Size(801, 36);
            guna2Panel1.TabIndex = 2;
            maximize2.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            maximize2.FillColor = Color.FromArgb(139, 152, 166);
            maximize2.IconColor = Color.White;
            maximize2.Location = new Point(707, 4);
            maximize2.Name = "maximize2";
            maximize2.Size = new Size(45, 29);
            maximize2.TabIndex = 3;
            maximize2.Text = "maximize2";
            guna2ControlBox2.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            guna2ControlBox2.ControlBoxType = Guna.UI2.WinForms.Enums.ControlBoxType.MinimizeBox;
            guna2ControlBox2.CustomizableEdges = customizableEdges23;
            guna2ControlBox2.FillColor = Color.FromArgb(144, 118, 147);
            guna2ControlBox2.IconColor = Color.White;
            guna2ControlBox2.Location = new Point(658, 4);
            guna2ControlBox2.Name = "guna2ControlBox2";
            guna2ControlBox2.ShadowDecoration.CustomizableEdges = customizableEdges24;
            guna2ControlBox2.Size = new Size(45, 29);
            guna2ControlBox2.TabIndex = 2;
            guna2ControlBox1.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            guna2ControlBox1.CustomizableEdges = customizableEdges25;
            guna2ControlBox1.FillColor = Color.FromArgb(144, 118, 147);
            guna2ControlBox1.IconColor = Color.White;
            guna2ControlBox1.Location = new Point(752, 4);
            guna2ControlBox1.Name = "guna2ControlBox1";
            guna2ControlBox1.ShadowDecoration.CustomizableEdges = customizableEdges26;
            guna2ControlBox1.Size = new Size(45, 29);
            guna2ControlBox1.TabIndex = 1;
            label1.AutoSize = true;
            label1.Font = new Font("Segoe UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point);
            label1.ForeColor = Color.White;
            label1.Location = new Point(12, 8);
            label1.Name = "label1";
            label1.Size = new Size(235, 20);
            label1.TabIndex = 0;
            label1.Text = "Create Mob By Nguyễn Đức Duy";
            guna2DragControl1.DockIndicatorTransparencyValue = 0.6D;
            guna2DragControl1.TargetControl = guna2Panel1;
            guna2DragControl1.UseTransparentDrag = true;
            openFileDialog1.FileName = "openFileDialog1";
            guna2BorderlessForm1.BorderRadius = 15;
            guna2BorderlessForm1.ContainerControl = this;
            guna2BorderlessForm1.DockIndicatorTransparencyValue = 0.6D;
            guna2BorderlessForm1.TransparentWhileDrag = true;
            guna2AnimateWindow1.TargetForm = this;
            checkSaveData.Enabled = true;
            checkSaveData.Interval = 1000;
            checkSaveData.Tick += checkSaveData_Tick;
            AutoScaleMode = AutoScaleMode.None;
            AutoSizeMode = AutoSizeMode.GrowAndShrink;
            ClientSize = new Size(801, 539);
            Controls.Add(guna2Panel2);
            Controls.Add(guna2Panel1);
            FormBorderStyle = FormBorderStyle.None;
            Icon = (Icon)resources.GetObject("$this.Icon");
            KeyPreview = true;
            Name = "MobForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "MobForm";
            TopMost = true;
            FormClosing += MobForm_FormClosing;
            Load += MobForm_Load;
            KeyDown += MobForm_KeyDown;
            ((System.ComponentModel.ISupportInitialize)picDefault).EndInit();
            guna2Panel3.ResumeLayout(false);
            guna2Panel3.PerformLayout();
            guna2Panel2.ResumeLayout(false);
            guna2Panel5.ResumeLayout(false);
            guna2Panel4.ResumeLayout(false);
            guna2Panel4.PerformLayout();
            guna2Panel1.ResumeLayout(false);
            guna2Panel1.PerformLayout();
            ResumeLayout(false);
        }

        #endregion
        private Guna.UI2.WinForms.Guna2GradientButton btnSaveCrop;
        public Guna.UI2.WinForms.Guna2PictureBox picDefault;
        private Guna.UI2.WinForms.Guna2GradientButton openHDSD;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel3;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel2;
        private Guna.UI2.WinForms.Guna2GradientButton btnEffectForm;
        private Guna.UI2.WinForms.Guna2GradientButton btnImportImage;
        private System.Windows.Forms.Timer UpdateExpired;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel1;
        private Label label1;
        private Guna.UI2.WinForms.Guna2DragControl guna2DragControl1;
        private OpenFileDialog openFileDialog1;
        private Guna.UI2.WinForms.Guna2BorderlessForm guna2BorderlessForm1;
        private Guna.UI2.WinForms.Guna2AnimateWindow guna2AnimateWindow1;
        private Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox2;
        private Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox1;
        public Guna.UI2.WinForms.Guna2CheckBox cbHasMobId;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel4;
        private Guna.UI2.WinForms.Guna2Panel guna2Panel5;
        public Guna.UI2.WinForms.Guna2TextBox txtIdMob;
        private Maximize maximize1;
        private System.Windows.Forms.Timer checkSaveData;
        private Guna.UI2.WinForms.Guna2GradientButton btnFastCrop;
        private Maximize maximize2;
    }
}